#!/usr/bin/env bash
# Downloads a curated set of Material Design Icons and generates
# plugin/src/mdi-icons.js from them. Run again to refresh or extend the set.
#
# MDI is Apache-2.0 (Pictogrammers) — see NOTICE.
set -euo pipefail

VERSION="7.4.47"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/com.ulanzi.matUlanziHa.ulanziPlugin/plugin/src/mdi-icons.js"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

ICONS="
lightbulb lightbulb-outline lightbulb-on lightbulb-group ceiling-light floor-lamp
desk-lamp lamp track-light led-strip chandelier string-lights
power power-plug power-plug-off power-socket-de toggle-switch toggle-switch-off flash
window-shutter window-shutter-open blinds blinds-horizontal garage garage-open
door door-open door-closed window-closed window-open curtains
lock lock-open-variant shield-home shield-lock key-variant
thermometer thermostat radiator radiator-off fire snowflake air-conditioner
water-percent weather-sunny weather-night weather-cloudy weather-partly-cloudy
fan air-filter air-purifier air-humidifier
speaker volume-high volume-medium volume-off play pause play-pause skip-next skip-previous
television music playlist-music cast
robot-vacuum washing-machine dishwasher fridge coffee kettle microwave toaster-oven
home home-outline sofa bed shower silverware-fork-knife desk stairs floor-plan
garage-variant tree flower pine-tree car ev-station
motion-sensor eye gauge battery battery-charging battery-alert wifi router-network
palette movie party-popper bell bell-off alarm run sleep water-pump
sun-thermometer weather-windy leaf recycle solar-power transmission-tower
account account-group map-marker calendar clock-outline timer-outline
cog dots-horizontal help-circle information-outline alert circle-outline
"

mkdir -p "$TMP/svg"
count=0
missing=""
for name in $ICONS; do
  url="https://cdn.jsdelivr.net/npm/@mdi/svg@$VERSION/svg/$name.svg"
  if curl -sS --fail --max-time 20 "$url" -o "$TMP/svg/$name.svg" 2>/dev/null; then
    count=$((count + 1))
  else
    missing="$missing $name"
  fi
done

{
  echo "/**"
  echo " * Material Design Icons, path data only, generated by tools/build-icons.sh."
  echo " * Source: @mdi/svg $VERSION — Apache-2.0 (Pictogrammers), see NOTICE."
  echo " *"
  echo " * Icons are referenced as \`mdi:<name>\` and tinted at render time, so the"
  echo " * same icon works on a light and on a dark key."
  echo " */"
  echo "(function (global) {"
  echo "  'use strict';"
  echo ""
  echo "  const MDI_ICONS = {"
  for file in "$TMP"/svg/*.svg; do
    name="$(basename "$file" .svg)"
    # Extract the single path's `d` attribute.
    d="$(sed -n 's/.*<path d="\([^"]*\)".*/\1/p' "$file" | head -1)"
    [ -z "$d" ] && continue
    echo "    '$name': '$d',"
  done
  echo "  };"
  echo ""
  echo "  global.MDI_ICONS = MDI_ICONS;"
  echo "})(window);"
} > "$OUT"

echo "downloaded: $count"
[ -n "$missing" ] && echo "missing:$missing"
echo "generated: $OUT ($(wc -c < "$OUT") bytes, $(grep -c "^    '" "$OUT") icons)"
